version: '2'

services:
  nginx:
    image: "nginx:1.12-alpine"
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
    environment:
      - DEFAULT_HOST=
    ports:
      - "80:80"
      - "443:443"
    restart: always
    logging:
      driver: none
    networks:
      - frontend-web

  nginx-gen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-gen
    command: "-notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    volumes_from: [nginx]
    volumes:
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - frontend-web

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    depends_on: [nginx-gen]
    volumes_from: [nginx]
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - ACME_TOS_HASH=cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b
    restart: always
    networks:
      - frontend-web

networks:
  frontend-web:
    external:
      name: frontend-web
